import { Router } from "express";
import accountingRouter from "./accounting";
import adminRouter from "./admin";
import auditRouter from "./audit";
import authRouter from "./auth";
import backupRouter from "./backup";
import branchesRouter from "./branches";
import cashierStatementRouter from "./cashier-statement";
import categoriesRouter from "./categories";
import customersRouter from "./customers";
import dashboardRouter from "./dashboard";
import documentPrintSettingsRouter from "./document-print-settings";
import employeesRouter from "./employees";
import expensesRouter from "./expenses";
import healthRouter from "./health";
import hrRouter from "./hr";
import inventoryRouter from "./inventory";
import kdsRouter from "./kds";
import licensesRouter from "./licenses";
import onyxRouter from "./onyx";
import ordersRouter from "./orders";
import printConfigRouter from "./print-config";
import printLogRouter from "./print-log";
import printerSettingsRouter from "./printer-settings";
import printersRouter from "./printers";
import productsRouter from "./products";
import purchasesRouter from "./purchases";
import recipesRouter from "./recipes";
import reportsRouter from "./reports";
import returnsRouter from "./returns";
import safesRouter from "./safes";
import settingsRouter from "./settings";
import shiftsRouter from "./shifts";
import suppliersRouter from "./suppliers";
import systemRouter from "./system";
import tablesRouter from "./tables";
import travelAdvancedRouter from "./travel-advanced";
import travelAtbRouter from "./travel-atb";
import travelBspRouter from "./travel-bsp";
import travelExtendedRouter from "./travel-extended";
import travelGdsRouter from "./travel-gds";
import travelPortalsRouter from "./travel-portals";
import travelRouter from "./travel";
import usersRouter from "./users";

const router = Router();
router.use(accountingRouter);
router.use(adminRouter);
router.use(auditRouter);
router.use(authRouter);
router.use(backupRouter);
router.use(branchesRouter);
router.use(cashierStatementRouter);
router.use(categoriesRouter);
router.use(customersRouter);
router.use(dashboardRouter);
router.use(documentPrintSettingsRouter);
router.use(employeesRouter);
router.use(expensesRouter);
router.use(healthRouter);
router.use(hrRouter);
router.use(inventoryRouter);
router.use(kdsRouter);
router.use(licensesRouter);
router.use(onyxRouter);
router.use(ordersRouter);
router.use(printConfigRouter);
router.use(printLogRouter);
router.use(printerSettingsRouter);
router.use(printersRouter);
router.use(productsRouter);
router.use(purchasesRouter);
router.use(recipesRouter);
router.use(reportsRouter);
router.use(returnsRouter);
router.use(safesRouter);
router.use(settingsRouter);
router.use(shiftsRouter);
router.use(suppliersRouter);
router.use(systemRouter);
router.use(tablesRouter);
router.use(travelAdvancedRouter);
router.use(travelAtbRouter);
router.use(travelBspRouter);
router.use(travelExtendedRouter);
router.use(travelGdsRouter);
router.use(travelPortalsRouter);
router.use(travelRouter);
router.use(usersRouter);

export default router;
